# Site Settings
title: Verisafe
email: info@verisafe.com.au # Update this to your actual email
description: >- # This helps with Google search results
  Verisafe offers organisations an easy and cost-effective solution for 
  verified Working with Children Check compliance and ongoing monitoring.
baseurl: "" # Leave empty for now
url: "http://localhost:4000"

# Build Settings
# theme: minima # Or leave blank if using your custom styles
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from the final website build
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor
  - about_files
  - contact_files
  - faq_files
  - home_files
  - pricing_files
